# Storage component adds blob storage for Quay to use
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./minio.persistentvolumeclaim.yaml
  - ./minio.service.yaml
  - ./minio.deployment.yaml
secretGenerator:
  - name: quay-storage
    # TODO(alecmerdler): Add certs here...
    literals:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
