# Clair component adds Clair v4 security scanner and its database.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: 
  - ./clair.deployment.yaml
  - ./clair.service.yaml
  - ./postgres.persistentvolumeclaim.yaml
  - ./postgres.deployment.yaml
  - ./postgres.service.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: clair-config-secret
