# Postgres component adds a Postgres database for Quay to use
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: 
  - ./postgres.persistentvolumeclaim.yaml
  - ./postgres.deployment.yaml
  - ./postgres.service.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: postgres-bootstrap
    literals:
      - init.sql=CREATE EXTENSION pg_trgm;
