# LocalStorage component adds registry blob storage using mounted `PersistentVolumes`.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: 
  - ./quay-datastore.persistentvolumeclaim.yaml
patchesStrategicMerge:
  # Add `volumeMount` to Quay app deployment for local storage.
  - ./quay.deployment.patch.yaml
