apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-datastore
  labels:
    quay-component: quay-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # FIXME(alecmerdler): How do we determine this size...?
      storage: 50Gi
