# Base assumes all other services (including database) are externally managed and only includes the Quay app itself.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: quay
resources: 
  - ./quay.role.yaml
  - ./quay.rolebinding.yaml
  - ./quay.deployment.yaml
  - ./quay.service.yaml
  - ./upgrade.deployment.yaml
