apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app
  labels:
    quay-component: quay-app
spec:
  replicas: 3
  selector:
    matchLabels:
      quay-component: quay-app
  template:
    metadata:
      labels:
        quay-component: quay-app
    spec:
      securityContext:
        fsGroup: 1001
      volumes:
        - name: configvolume
          secret:
            secretName: quay-config-secret
      containers:
        - name: quay-app
          image: quay.io/projectquay/quay
          env:
            - name: QE_K8S_CONFIG_SECRET
              # FIXME(alecmerdler): Using `vars` is kinda ugly because it's basically templating, but this needs to be the generated `Secret` name...
              value: $(QE_K8S_CONFIG_SECRET)
            - name: QE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGLOG
              value: "true"
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - curl
                - '-k'
                - 'https://localhost:8443/health/instance'
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: configvolume
              readOnly: false
              mountPath: /conf/stack
